FROM python:3.13-alpine

RUN apk add --no-cache ca-certificates

ENV HOST=0.0.0.0
ENV PORT=39173
ENV UPSTREAM_BASE=https://api.xiaomimimo.com
ENV UPSTREAM_USER_AGENT=Python-urllib/3
ENV MAX_429_WAIT_MS=180000
ENV DEFAULT_MODEL=mimo-auto
ENV CLIENT_FILE=/data/client
ENV JWT_FILE=/data/jwt
ENV GOMEMLIMIT=24MiB
ENV GOGC=50
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV MALLOC_ARENA_MAX=1

WORKDIR /app
COPY proxy.py /app/proxy.py

EXPOSE 39173
VOLUME ["/data"]

ENTRYPOINT ["python", "/app/proxy.py"]
